# ansible-playbook -i ~/ansible/hosts /playbooks/distribute_ssh_key.yml
---
- hosts: allpi
  gather_facts: yes

  tasks:
    - name: Set authorized key took from file
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"
