    - name:  Copy roms using smbclient
      become: yes
      command: smbclient {{ smb_rom_share }} -N -c 'prompt;recurse;cd {{ smb_rom_folder }};mget *'
      args:
        chdir: /home/pi/RetroPie/roms

    - name: Copy es_systems.cfg template
      become: yes
      template: src=../templates/emulationstation/es_systems.cfg dest=/etc/emulationstation/es_systems.cfg

    - name: Create downloaded_images folder
      file: path=~/.emulationstation/downloaded_images state=directory

    - name:  Copy downloaded_images using smbclient
      command: smbclient {{ smb_rom_share }} -N -c 'prompt;recurse;cd {{ smb_es_folder }}/downloaded_images;mget *'
      args:
        chdir: /home/pi/.emulationstation/downloaded_images

    - name: Create gamelists folder
      file: path=~/.emulationstation/gamelists state=directory

    - name:  Copy gamelists using smbclient
      command: smbclient {{ smb_rom_share }} -N -c 'prompt;recurse;cd {{ smb_es_folder }}/gamelists;mget *'
      args:
        chdir: ~/.emulationstation/gamelists