- name: Create config directory
  file:
    path: /docker/grafana
    state: directory

- name: Create docker-compose.yml file
  template:
    src: 'docker-compose.yml.grafana.j2'
    dest: "/docker/grafana/docker-compose.yml"

- name: Run the stuff....
  docker_service:
    project_src: /docker/grafana

- docker_service:
    project_src: /docker/grafana
    restarted: true

