---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    image: joepublic/molecule-debian:9
    command: /lib/systemd/systemd
    pull: false
    privileged: true
    published_ports:
      - 8123:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian10
    image: joepublic/molecule-debian:10
    command: /lib/systemd/systemd
    pull: false
    privileged: true
    published_ports:
      - 8124:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu18.04
    image: joepublic/molecule-ubuntu:18.04
    command: /lib/systemd/systemd
    pull: false
    privileged: true
    published_ports:
      - 8125:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu18.10
    image: joepublic/molecule-ubuntu:18.10
    command: /lib/systemd/systemd
    pull: false
    privileged: true
    published_ports:
      - 8126:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7
    image: joepublic/molecule-centos:7
    command: /usr/sbin/init
    pull: false
    privileged: true
    published_ports:
      - 8127:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora28
    image: joepublic/molecule-fedora:28
    command: /usr/sbin/init
    pull: false
    privileged: true
    published_ports:
      - 8128:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora29
    image: joepublic/molecule-fedora:29
    command: /usr/sbin/init
    pull: false
    privileged: true
    published_ports:
      - 8129:8123
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
    ANSIBLE_GATHER_TIMEOUT: "20"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
    enabled: false
