esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

<<: !include wifi.yaml
<<: !include mqtt.yaml

# Status LED, the built-in LED is on D4
status_led:
  pin:
    number: D4
    inverted: False

# Enable logging
logger: 

ota:
  password: 'PWN'

web_server:
  port: 80

sensor:
  - platform: uptime
    name: "Uptime Sensor $devicename"

  # Wifi is a builtin sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor $devicename"
    update_interval: 10s


# Flow meter <-> Wemos D1 mini
# Red	         +5V (!)
# Yellow	     D4
# Black	         GND

  - platform: pulse_counter
    name: "Flow door sensor $devicename"
    pin: D2
    update_interval: 6s  # 1/10th of a minute.
    unit_of_measurement: "l/m"
    filters:
      - filter_out: nan
      - sliding_window_moving_average:
          window_size: 1
          send_every: 1
      - lambda: |-
          return ( x / 100 );
#      - unique:

switch:
  - platform: restart
    name: "Restart controller $devicename"

