---
#
# To run this playbook type the following command from the commandline:
# ansible-playbook  -u pi ansible.yml 

# (c) Marco Verleun <marco@marcoach.nl>
# 
# This playbook is licensed under a GPL license. It is written
# to provision Raspberry Pi's used with the demo setup from PWN.
#
# We only configure localhost with this playbook.
# It's a bit odd, but it works great...
- hosts: localhost

  # We need to elevate our priviliges for the tasks we will run
  become: yes
  become_user: root

  # Choose the version of python that will be used
  vars:
    ansible_python_interpreter: /usr/bin/python3
    

  tasks:
    # Not a real task, but if it fails something is wrong with the installation
    # of ansible
    - debug: msg="Ansible running in {{ansible_lsb.id}}!"

  roles:
    - ansible
