substitutions:
  # Iedere controller heeft ook een eigen naam. Deze moet uniek zijn.
  devicename: "controller_6"
  upper_devicename: "Controller_6"

<<: !include includes/wifi.yaml
<<: !include includes/mqtt.yaml
<<: !include includes/flowmeter-controller.yaml
